### ISSUE TITLE
default language selection on config.php page not working properly

### ISSUE THREAD

**Issue by ChristianStrotkoetter** [madnetdev/regmon-os#14]
If default language = german is chosen, the app still starts using the english version.

**Comment by madnetdev** [comment]
Default_Language works only if you have the Use_Multi_Language_Selector = off.
Else the cookie will say what Language is the selected one.
In case it is a fresh start and you do not have any cookie yet then the Browser string will give as the Language.
Uncomment line 81 in class.language.php to check your Browser string language score.
