### ISSUE TITLE
rename "comments" -> "notes" in SQL-table and in code

### ISSUE THREAD

**Issue by ChristianStrotkoetter** [madnetdev/regmon-os#18]
please use "notes" (german: "Notizen") instead of "comments" in SQL-table and in code

**Comment by ChristianStrotkoetter** [comment]
This may be done by me or Kevin as well (search & replace in a proper manner), but I am not sure about side effects etc.
@madnetdev What do you think? Should we do this kind of stuff on our own?

**Comment by madnetdev** [comment]
As we have already said this depends on the case.
Here we need to replace strings like (COMMENT, Comments, comments, Comment, comment, etc),
but there are already a lot of (Note, note, Note_N, etc).
In this case we should replace (Note, etc) with something else first.
If that is not important you better not get into this adventure.

**Comment by madnetdev** [comment]
Please test.
