### ISSUE TITLE
How to use docker-compose-dev?

### ISSUE THREAD

**Issue by madnetdev** [madnetdev/regmon-os#26]
Before update I used :
`docker-compose build`
After update I tried the following with errors.
```
docker-compose-dev build
docker-compose-dev.yml build
.\docker-compose-dev.yml build
```
![2023-09-26 173745](https://github.com/madnetdev/regmon-os/assets/115354386/0811b149-bdfe-481e-a3d1-271f99a4385e)

In order to work I copy `docker-compose-dev.yml` to `docker-compose.yml`

Please also write info about how to use in README file.

**Comment by ChristianStrotkoetter** [comment]
I'm on my mobile right now, but please try right click in VS Code on docker-compose-dev.yml and click "Docker up" or something like that. This worked for me.

@kencreek please provide more info in Readme, if necessary, thanks!

**Comment by kencreek** [comment]
Hey Dimi,
as Christian already told you can right click on the script docker-compose-dev.yml and click docker up or down.
If you do docker up then the following command will be executed:
docker compose -f "docker-compose-dev.yml" up -d --build

**Comment by madnetdev** [comment]
You are probably referring to a docker plugin in VS Code which I don't have.
Also it should work without VS Code.

This works but need info in README.
`docker compose -f "docker-compose-dev.yml" up -d --build`

**Comment by ChristianStrotkoetter** [comment]
yeah, we will add this info besides many others things in the new README and documentation - coming soon.
