### ISSUE TITLE
Further procedure with "TODO" comments in code

### ISSUE THREAD

**Issue by ChristianStrotkoetter** [madnetdev/regmon-os#34]
There are 25 "//TODO" comments in 15 files right now.
Should we just leave them for now, or is there anything we need to take care of before publishing?

**Comment by madnetdev** [comment]
I checked, removed, fixed some.
Most of them are enhancements, 
some are for the future 
and some are like questions  "maybe we need all forms for export even disabled if they have data".

Nothing crucial as I see it.
