### ISSUE TITLE
results.php page: athlete data is not loaded after selection

### ISSUE THREAD

**Issue by ChristianStrotkoetter** [madnetdev/regmon-os#7]
groups, athletes, forms, forms data etc. can be chosen:
![grafik](https://github.com/madnetdev/regmon-os/assets/49678499/357946ac-c7d6-4681-a031-ca09b4e48d33)
but there is no athlete data displayed or loaded.
![grafik](https://github.com/madnetdev/regmon-os/assets/49678499/eb1b34f3-ec73-417b-a4d2-09766ec98643)

**Comment by madnetdev** [comment]
I cannot reproduce

**Comment by ChristianStrotkoetter** [comment]
this issue is related to the Firefox-browser
(as far as I can see, chrome works fine)
